-- Reset the sequence to the max ID + 1
SELECT setval('quiz_questions_id_seq', (SELECT MAX(id) FROM quiz_questions));

-- Insert K21 2025 quiz questions (will only appear in /fimdeano theme)
INSERT INTO quiz_questions (question, question_en, category_id, options, options_en, correct_answer, explanation, explanation_en, theme_id) VALUES
('Temos uma K21nica que faz escalas, desenha muito, e curte muito construir Legos maneiros com seu filho. Quem é ela?', 'Temos uma K21nica que faz escalas, desenha muito, e curte muito construir Legos maneiros com seu filho. Quem é ela?', NULL, '["Allan", "Avelino", "Fernanda Magalhães", "Murilo"]', '["Allan", "Avelino", "Fernanda Magalhães", "Murilo"]', '0', 'A resposta correta é Allan.', 'A resposta correta é Allan.', '4179fd0b-16f4-4761-9cb1-7111bf344bf5'),
('Onde nasceu o nome da K21?', 'Onde nasceu o nome da K21?', NULL, '["Na praia de Copacabana", "Em um laboratório da PUC - Rio", "Na praça de alimentação do shopping Leblon", "Na batata de Marechal"]', '["Na praia de Copacabana", "Em um laboratório da PUC - Rio", "Na praça de alimentação do shopping Leblon", "Na batata de Marechal"]', '2', 'A resposta correta é na praça de alimentação do shopping Leblon.', 'A resposta correta é na praça de alimentação do shopping Leblon.', '4179fd0b-16f4-4761-9cb1-7111bf344bf5'),
('Quantas edições do SGRio já tivemos?', 'Quantas edições do SGRio já tivemos?', NULL, '["10", "11", "12", "13"]', '["10", "11", "12", "13"]', '1', 'A resposta correta é 11 edições.', 'A resposta correta é 11 edições.', '4179fd0b-16f4-4761-9cb1-7111bf344bf5'),
('Quando foi o lançamento da marca Nower?', 'Quando foi o lançamento da marca Nower?', NULL, '["Janeiro de 2024", "Setembro de 2023", "Fevereiro de 2023", "Março de 2025"]', '["Janeiro de 2024", "Setembro de 2023", "Fevereiro de 2023", "Março de 2025"]', '1', 'A resposta correta é Setembro de 2023.', 'A resposta correta é Setembro de 2023.', '4179fd0b-16f4-4761-9cb1-7111bf344bf5'),
('Temos uma K21nica virando fotógrafo amador de eventos esportivos. Quem é?', 'Temos uma K21nica virando fotógrafo amador de eventos esportivos. Quem é?', NULL, '["Garrido", "Fernanda Magalhães", "Rafinha", "Raphael Chewie"]', '["Garrido", "Fernanda Magalhães", "Rafinha", "Raphael Chewie"]', '0', 'A resposta correta é Garrido.', 'A resposta correta é Garrido.', '4179fd0b-16f4-4761-9cb1-7111bf344bf5'),
('Qual dessas 3 pessoas não joga tênis?', 'Qual dessas 3 pessoas não joga tênis?', NULL, '["Guga", "Fernanda Magalhães", "Garrido", "Dani Prevot"]', '["Guga", "Fernanda Magalhães", "Garrido", "Dani Prevot"]', '3', 'A resposta correta é Dani Prevot.', 'A resposta correta é Dani Prevot.', '4179fd0b-16f4-4761-9cb1-7111bf344bf5'),
('O primeiro EVDnC rodado pela K21 nos ajudou a pescar um dos nossos consultores?', 'O primeiro EVDnC rodado pela K21 nos ajudou a pescar um dos nossos consultores?', NULL, '["Lucas", "Isac", "Natasha", "Fernanda Morelli"]', '["Lucas", "Isac", "Natasha", "Fernanda Morelli"]', '0', 'A resposta correta é Lucas.', 'A resposta correta é Lucas.', '4179fd0b-16f4-4761-9cb1-7111bf344bf5'),
('Já trabalhou diretamente na C&A antes de vir atuar com a gente da Nower e K21?', 'Já trabalhou diretamente na C&A antes de vir atuar com a gente da Nower e K21?', NULL, '["Dani Prevot e Raphael Chewie", "Rafinha e Samira", "Paulo Cassin e Fê Morelli", "Renan e Natasha"]', '["Dani Prevot e Raphael Chewie", "Rafinha e Samira", "Paulo Cassin e Fê Morelli", "Renan e Natasha"]', '2', 'A resposta correta é Paulo Cassin e Fê Morelli.', 'A resposta correta é Paulo Cassin e Fê Morelli.', '4179fd0b-16f4-4761-9cb1-7111bf344bf5'),
('Quem é o maior agilista que já trabalhou na K21?', 'Quem é o maior agilista que já trabalhou na K21?', NULL, '["Toledo", "Avelino", "Raphael Chewie", "Garrido"]', '["Toledo", "Avelino", "Raphael Chewie", "Garrido"]', '1', 'A resposta correta é Avelino.', 'A resposta correta é Avelino.', '4179fd0b-16f4-4761-9cb1-7111bf344bf5'),
('Quantos alunos a K21 já formou?', 'Quantos alunos a K21 já formou?', NULL, '["Cerca de 30 mil", "Entre 15 e 20 mil alunos", "Mais de 50 mil alunos", "7 pessoas"]', '["Cerca de 30 mil", "Entre 15 e 20 mil alunos", "Mais de 50 mil alunos", "7 pessoas"]', '2', 'A resposta correta é mais de 50 mil alunos.', 'A resposta correta é mais de 50 mil alunos.', '4179fd0b-16f4-4761-9cb1-7111bf344bf5');