-- Reset the sequence to start after the highest existing ID
SELECT setval('quiz_questions_id_seq', (SELECT MAX(id) FROM quiz_questions) + 1);

-- Now insert 25 questions for the oscrias theme (The Crias Challenge)
INSERT INTO quiz_questions (theme_id, category_id, question, question_en, options, options_en, correct_answer, explanation, explanation_en)
VALUES
-- American History (5 questions)
('03f32fe5-9350-4fb1-b1d9-351242c33f59', 'american_history', 
 'Qual foi o ano da Declaração de Independência dos Estados Unidos?', 
 'What year was the United States Declaration of Independence?',
 '{"a": "1774", "b": "1776", "c": "1778", "d": "1780"}',
 '{"a": "1774", "b": "1776", "c": "1778", "d": "1780"}',
 'b', 
 'A Declaração de Independência dos Estados Unidos foi adotada em 4 de julho de 1776.',
 'The United States Declaration of Independence was adopted on July 4, 1776.'),

('03f32fe5-9350-4fb1-b1d9-351242c33f59', 'american_history',
 'Quem foi o primeiro presidente dos Estados Unidos?',
 'Who was the first president of the United States?',
 '{"a": "Thomas Jefferson", "b": "John Adams", "c": "George Washington", "d": "Benjamin Franklin"}',
 '{"a": "Thomas Jefferson", "b": "John Adams", "c": "George Washington", "d": "Benjamin Franklin"}',
 'c',
 'George Washington foi o primeiro presidente dos Estados Unidos, servindo de 1789 a 1797.',
 'George Washington was the first president of the United States, serving from 1789 to 1797.'),

('03f32fe5-9350-4fb1-b1d9-351242c33f59', 'american_history',
 'Qual guerra civil americana ocorreu entre 1861 e 1865?',
 'Which American civil war occurred between 1861 and 1865?',
 '{"a": "Guerra da Independência", "b": "Guerra Civil Americana", "c": "Guerra Mexicano-Americana", "d": "Guerra de 1812"}',
 '{"a": "Revolutionary War", "b": "American Civil War", "c": "Mexican-American War", "d": "War of 1812"}',
 'b',
 'A Guerra Civil Americana foi travada entre os estados do Norte (União) e do Sul (Confederação) de 1861 a 1865.',
 'The American Civil War was fought between the Northern states (Union) and Southern states (Confederacy) from 1861 to 1865.'),

('03f32fe5-9350-4fb1-b1d9-351242c33f59', 'american_history',
 'Qual presidente americano aboliu a escravidão?',
 'Which American president abolished slavery?',
 '{"a": "Andrew Jackson", "b": "Abraham Lincoln", "c": "Ulysses S. Grant", "d": "Theodore Roosevelt"}',
 '{"a": "Andrew Jackson", "b": "Abraham Lincoln", "c": "Ulysses S. Grant", "d": "Theodore Roosevelt"}',
 'b',
 'Abraham Lincoln emitiu a Proclamação de Emancipação em 1863 e a 13ª Emenda foi ratificada em 1865.',
 'Abraham Lincoln issued the Emancipation Proclamation in 1863 and the 13th Amendment was ratified in 1865.'),

('03f32fe5-9350-4fb1-b1d9-351242c33f59', 'american_history',
 'Em que ano os Estados Unidos entraram na Segunda Guerra Mundial?',
 'In what year did the United States enter World War II?',
 '{"a": "1939", "b": "1940", "c": "1941", "d": "1942"}',
 '{"a": "1939", "b": "1940", "c": "1941", "d": "1942"}',
 'c',
 'Os EUA entraram na Segunda Guerra Mundial em dezembro de 1941, após o ataque a Pearl Harbor.',
 'The US entered World War II in December 1941, after the attack on Pearl Harbor.'),

-- World History (5 questions)
('03f32fe5-9350-4fb1-b1d9-351242c33f59', 'world_history',
 'Qual civilização construiu as pirâmides de Gizé?',
 'Which civilization built the pyramids of Giza?',
 '{"a": "Romanos", "b": "Gregos", "c": "Egípcios", "d": "Maias"}',
 '{"a": "Romans", "b": "Greeks", "c": "Egyptians", "d": "Mayans"}',
 'c',
 'As pirâmides de Gizé foram construídas pelos antigos egípcios há cerca de 4.500 anos.',
 'The pyramids of Giza were built by the ancient Egyptians about 4,500 years ago.'),

('03f32fe5-9350-4fb1-b1d9-351242c33f59', 'world_history',
 'Qual império foi governado por Júlio César?',
 'Which empire was ruled by Julius Caesar?',
 '{"a": "Império Grego", "b": "Império Romano", "c": "Império Persa", "d": "Império Mongol"}',
 '{"a": "Greek Empire", "b": "Roman Empire", "c": "Persian Empire", "d": "Mongol Empire"}',
 'b',
 'Júlio César foi um líder militar e político do Império Romano no século I a.C.',
 'Julius Caesar was a military and political leader of the Roman Empire in the 1st century BC.'),

('03f32fe5-9350-4fb1-b1d9-351242c33f59', 'world_history',
 'Em que ano começou a Primeira Guerra Mundial?',
 'In what year did World War I begin?',
 '{"a": "1912", "b": "1914", "c": "1916", "d": "1918"}',
 '{"a": "1912", "b": "1914", "c": "1916", "d": "1918"}',
 'b',
 'A Primeira Guerra Mundial começou em 1914 e terminou em 1918.',
 'World War I began in 1914 and ended in 1918.'),

('03f32fe5-9350-4fb1-b1d9-351242c33f59', 'world_history',
 'Qual país foi o berço da Revolução Industrial?',
 'Which country was the birthplace of the Industrial Revolution?',
 '{"a": "França", "b": "Alemanha", "c": "Inglaterra", "d": "Estados Unidos"}',
 '{"a": "France", "b": "Germany", "c": "England", "d": "United States"}',
 'c',
 'A Revolução Industrial começou na Inglaterra no final do século XVIII.',
 'The Industrial Revolution began in England in the late 18th century.'),

('03f32fe5-9350-4fb1-b1d9-351242c33f59', 'world_history',
 'Quem foi o líder da Alemanha durante a Segunda Guerra Mundial?',
 'Who was the leader of Germany during World War II?',
 '{"a": "Otto von Bismarck", "b": "Adolf Hitler", "c": "Kaiser Wilhelm II", "d": "Joseph Stalin"}',
 '{"a": "Otto von Bismarck", "b": "Adolf Hitler", "c": "Kaiser Wilhelm II", "d": "Joseph Stalin"}',
 'b',
 'Adolf Hitler foi o líder da Alemanha Nazista de 1933 a 1945.',
 'Adolf Hitler was the leader of Nazi Germany from 1933 to 1945.'),

-- Geography (5 questions)
('03f32fe5-9350-4fb1-b1d9-351242c33f59', 'geography',
 'Qual é o maior oceano do mundo?',
 'What is the largest ocean in the world?',
 '{"a": "Oceano Atlântico", "b": "Oceano Índico", "c": "Oceano Pacífico", "d": "Oceano Ártico"}',
 '{"a": "Atlantic Ocean", "b": "Indian Ocean", "c": "Pacific Ocean", "d": "Arctic Ocean"}',
 'c',
 'O Oceano Pacífico é o maior oceano, cobrindo mais de 165 milhões de km².',
 'The Pacific Ocean is the largest ocean, covering more than 165 million km².'),

('03f32fe5-9350-4fb1-b1d9-351242c33f59', 'geography',
 'Qual é o rio mais longo do mundo?',
 'What is the longest river in the world?',
 '{"a": "Rio Amazonas", "b": "Rio Nilo", "c": "Rio Mississippi", "d": "Rio Yangtze"}',
 '{"a": "Amazon River", "b": "Nile River", "c": "Mississippi River", "d": "Yangtze River"}',
 'b',
 'O Rio Nilo, com aproximadamente 6.650 km, é considerado o rio mais longo do mundo.',
 'The Nile River, at approximately 6,650 km, is considered the longest river in the world.'),

('03f32fe5-9350-4fb1-b1d9-351242c33f59', 'geography',
 'Qual é o maior país do mundo em área territorial?',
 'What is the largest country in the world by land area?',
 '{"a": "China", "b": "Estados Unidos", "c": "Canadá", "d": "Rússia"}',
 '{"a": "China", "b": "United States", "c": "Canada", "d": "Russia"}',
 'd',
 'A Rússia é o maior país do mundo, com mais de 17 milhões de km².',
 'Russia is the largest country in the world, with more than 17 million km².'),

('03f32fe5-9350-4fb1-b1d9-351242c33f59', 'geography',
 'Qual é a montanha mais alta do mundo?',
 'What is the highest mountain in the world?',
 '{"a": "Monte Kilimanjaro", "b": "Monte Everest", "c": "Monte McKinley", "d": "Monte Fuji"}',
 '{"a": "Mount Kilimanjaro", "b": "Mount Everest", "c": "Mount McKinley", "d": "Mount Fuji"}',
 'b',
 'O Monte Everest, com 8.849 metros, é a montanha mais alta do mundo.',
 'Mount Everest, at 8,849 meters, is the highest mountain in the world.'),

('03f32fe5-9350-4fb1-b1d9-351242c33f59', 'geography',
 'Quantos continentes existem no mundo?',
 'How many continents are there in the world?',
 '{"a": "5", "b": "6", "c": "7", "d": "8"}',
 '{"a": "5", "b": "6", "c": "7", "d": "8"}',
 'c',
 'Existem 7 continentes: África, Antártida, Ásia, Europa, América do Norte, Oceania e América do Sul.',
 'There are 7 continents: Africa, Antarctica, Asia, Europe, North America, Oceania, and South America.'),

-- Science (5 questions)
('03f32fe5-9350-4fb1-b1d9-351242c33f59', 'science',
 'Qual é o planeta mais próximo do Sol?',
 'What is the closest planet to the Sun?',
 '{"a": "Vênus", "b": "Marte", "c": "Mercúrio", "d": "Terra"}',
 '{"a": "Venus", "b": "Mars", "c": "Mercury", "d": "Earth"}',
 'c',
 'Mercúrio é o planeta mais próximo do Sol, a uma distância média de 58 milhões de km.',
 'Mercury is the closest planet to the Sun, at an average distance of 58 million km.'),

('03f32fe5-9350-4fb1-b1d9-351242c33f59', 'science',
 'Qual é a fórmula química da água?',
 'What is the chemical formula for water?',
 '{"a": "CO2", "b": "H2O", "c": "NaCl", "d": "O2"}',
 '{"a": "CO2", "b": "H2O", "c": "NaCl", "d": "O2"}',
 'b',
 'A fórmula química da água é H2O - duas moléculas de hidrogênio e uma de oxigênio.',
 'The chemical formula for water is H2O - two hydrogen molecules and one oxygen molecule.'),

('03f32fe5-9350-4fb1-b1d9-351242c33f59', 'science',
 'Quantos ossos tem o corpo humano adulto?',
 'How many bones does an adult human body have?',
 '{"a": "186", "b": "206", "c": "226", "d": "256"}',
 '{"a": "186", "b": "206", "c": "226", "d": "256"}',
 'b',
 'O corpo humano adulto tem 206 ossos.',
 'The adult human body has 206 bones.'),

('03f32fe5-9350-4fb1-b1d9-351242c33f59', 'science',
 'Qual é o maior órgão do corpo humano?',
 'What is the largest organ in the human body?',
 '{"a": "Coração", "b": "Fígado", "c": "Pele", "d": "Pulmões"}',
 '{"a": "Heart", "b": "Liver", "c": "Skin", "d": "Lungs"}',
 'c',
 'A pele é o maior órgão do corpo humano, pesando cerca de 3,6 kg.',
 'The skin is the largest organ in the human body, weighing about 3.6 kg.'),

('03f32fe5-9350-4fb1-b1d9-351242c33f59', 'science',
 'Qual cientista desenvolveu a teoria da relatividade?',
 'Which scientist developed the theory of relativity?',
 '{"a": "Isaac Newton", "b": "Galileu Galilei", "c": "Albert Einstein", "d": "Stephen Hawking"}',
 '{"a": "Isaac Newton", "b": "Galileo Galilei", "c": "Albert Einstein", "d": "Stephen Hawking"}',
 'c',
 'Albert Einstein desenvolveu a teoria da relatividade no início do século XX.',
 'Albert Einstein developed the theory of relativity in the early 20th century.'),

-- Important Events (5 questions)
('03f32fe5-9350-4fb1-b1d9-351242c33f59', 'important_events',
 'Em que ano o homem pisou na Lua pela primeira vez?',
 'In what year did man first walk on the Moon?',
 '{"a": "1967", "b": "1969", "c": "1971", "d": "1973"}',
 '{"a": "1967", "b": "1969", "c": "1971", "d": "1973"}',
 'b',
 'Neil Armstrong foi o primeiro homem a pisar na Lua em 20 de julho de 1969.',
 'Neil Armstrong was the first man to walk on the Moon on July 20, 1969.'),

('03f32fe5-9350-4fb1-b1d9-351242c33f59', 'important_events',
 'Quando caiu o Muro de Berlim?',
 'When did the Berlin Wall fall?',
 '{"a": "1987", "b": "1989", "c": "1991", "d": "1993"}',
 '{"a": "1987", "b": "1989", "c": "1991", "d": "1993"}',
 'b',
 'O Muro de Berlim caiu em 9 de novembro de 1989.',
 'The Berlin Wall fell on November 9, 1989.'),

('03f32fe5-9350-4fb1-b1d9-351242c33f59', 'important_events',
 'Em que ano ocorreu o ataque às Torres Gêmeas?',
 'In what year did the Twin Towers attack occur?',
 '{"a": "1999", "b": "2001", "c": "2003", "d": "2005"}',
 '{"a": "1999", "b": "2001", "c": "2003", "d": "2005"}',
 'b',
 'Os ataques de 11 de setembro ocorreram em 2001, quando aviões atingiram o World Trade Center.',
 'The September 11 attacks occurred in 2001, when planes hit the World Trade Center.'),

('03f32fe5-9350-4fb1-b1d9-351242c33f59', 'important_events',
 'Qual pandemia assolou o mundo em 2020?',
 'Which pandemic swept the world in 2020?',
 '{"a": "H1N1", "b": "SARS", "c": "COVID-19", "d": "Ebola"}',
 '{"a": "H1N1", "b": "SARS", "c": "COVID-19", "d": "Ebola"}',
 'c',
 'A pandemia de COVID-19 começou em 2019 na China e se espalhou globalmente em 2020.',
 'The COVID-19 pandemic began in 2019 in China and spread globally in 2020.'),

('03f32fe5-9350-4fb1-b1d9-351242c33f59', 'important_events',
 'Em que ano foi fundada a ONU (Organização das Nações Unidas)?',
 'In what year was the UN (United Nations) founded?',
 '{"a": "1940", "b": "1945", "c": "1950", "d": "1955"}',
 '{"a": "1940", "b": "1945", "c": "1950", "d": "1955"}',
 'b',
 'A ONU foi fundada em 24 de outubro de 1945, após a Segunda Guerra Mundial.',
 'The UN was founded on October 24, 1945, after World War II.');