
-- Insert quiz questions with both Portuguese and English translations
INSERT INTO quiz_questions (
    id, question, category_id, options, correct_answer, explanation,
    question_en, options_en, explanation_en
) VALUES
(1, 'Qual é uma das principais disfunções que pode ocorrer em um Scrum Team quando a Transparência é comprometida?', 'fundamentals', '[{"id":"a","text":"Aumento na produtividade da equipe"},{"id":"b","text":"Tomada de decisões baseada em informações incompletas ou incorretas"},{"id":"c","text":"Maior colaboração entre os membros da equipe"},{"id":"d","text":"Redução no tempo de desenvolvimento do produto"}]', 'b', 'Quando a Transparência é comprometida, os membros do Scrum Team tomam decisões baseadas em informações incompletas ou incorretas, levando a resultados inadequados e perda de confiança.', 'What is one of the main dysfunctions that can occur in a Scrum Team when Transparency is compromised?', '[{"id":"a","text":"Increase in team productivity"},{"id":"b","text":"Decision-making based on incomplete or incorrect information"},{"id":"c","text":"Greater collaboration among team members"},{"id":"d","text":"Reduction in product development time"}]', 'When Transparency is compromised, Scrum Team members make decisions based on incomplete or incorrect information, leading to inadequate results and a loss of trust.'),

(2, 'Qual disfunção pode ocorrer quando o Product Owner não mantém o Product Backlog adequadamente refinado?', 'roles', '[{"id":"a","text":"Equipe mais focada nos objetivos do produto"},{"id":"b","text":"Sprints com maior valor de entrega"},{"id":"c","text":"Sprint Planning ineficiente e itens mal compreendidos pela equipe"},{"id":"d","text":"Aumento na velocidade de desenvolvimento"}]', 'c', 'Quando o Product Backlog não é adequadamente refinado, o Sprint Planning torna-se ineficiente e os itens do backlog são mal compreendidos pela equipe, resultando em atrasos e entregas de menor valor.', 'Which dysfunction can occur when the Product Owner does not keep the Product Backlog properly refined?', '[{"id":"a","text":"Team more focused on the product objectives"},{"id":"b","text":"Sprints with higher delivery value"},{"id":"c","text":"Inefficient Sprint Planning and items poorly understood by the team"},{"id":"d","text":"Increase in development speed"}]', 'When the Product Backlog is not properly refined, Sprint Planning becomes inefficient and backlog items are poorly understood by the team, resulting in delays and lower-value deliveries.'),

(3, 'Qual é uma disfunção comum quando o Scrum Master não remove impedimentos de forma eficaz?', 'roles', '[{"id":"a","text":"A equipe se torna mais autônoma e eficiente"},{"id":"b","text":"Redução na qualidade das entregas e frustração da equipe"},{"id":"c","text":"Maior velocidade de entrega"},{"id":"d","text":"Melhoria contínua mais rápida"}]', 'b', 'Quando o Scrum Master falha em remover impedimentos de forma eficaz, a equipe enfrenta obstáculos constantes que reduzem a qualidade das entregas e causam frustração, diminuindo a produtividade e o moral.', 'What is a common dysfunction when the Scrum Master does not remove impediments effectively?', '[{"id":"a","text":"The team becomes more autonomous and efficient"},{"id":"b","text":"Reduced delivery quality and team frustration"},{"id":"c","text":"Higher delivery speed"},{"id":"d","text":"Faster continuous improvement"}]', 'When the Scrum Master fails to remove impediments effectively, the team faces constant obstacles that lower delivery quality and cause frustration, decreasing productivity and morale.'),

(4, 'Qual disfunção pode ocorrer quando as Daily Scrums se transformam em reuniões de status para gerentes?', 'events', '[{"id":"a","text":"Maior colaboração entre os membros da equipe"},{"id":"b","text":"Melhor comunicação de impedimentos"},{"id":"c","text":"Redução do foco na inspeção e adaptação diária"},{"id":"d","text":"Maior engajamento dos desenvolvedores na reunião"}]', 'c', 'Quando as Daily Scrums se transformam em reuniões de status, perde-se o foco na inspeção e adaptação diária. Em vez de sincronizar e identificar impedimentos, o evento torna-se apenas uma sessão de prestação de contas.', 'Which dysfunction can occur when Daily Scrums turn into status meetings for managers?', '[{"id":"a","text":"Increased collaboration among team members"},{"id":"b","text":"Better communication of impediments"},{"id":"c","text":"Reduced focus on daily inspection and adaptation"},{"id":"d","text":"Greater developer engagement in the meeting"}]', 'When Daily Scrums turn into status meetings, the focus on daily inspection and adaptation is lost. Instead of synchronizing and surfacing impediments, the event becomes merely an accountability session.'),

(5, 'Qual disfunção está associada a equipes que não conduzem adequadamente as Sprint Retrospectives?', 'events', '[{"id":"a","text":"Maior capacidade de se adaptar às mudanças"},{"id":"b","text":"Repetição constante dos mesmos erros e falta de melhoria contínua"},{"id":"c","text":"Redução no tempo de desenvolvimento"},{"id":"d","text":"Maior qualidade do produto"}]', 'b', 'Equipes que negligenciam as Sprint Retrospectives perdem a oportunidade de aprender com sua experiência, levando à repetição de erros e falta de melhoria contínua nos processos de trabalho e relacionamentos interpessoais.', 'Which dysfunction is associated with teams that do not properly conduct Sprint Retrospectives?', '[{"id":"a","text":"Greater ability to adapt to change"},{"id":"b","text":"Constant repetition of the same mistakes and lack of continuous improvement"},{"id":"c","text":"Reduced development time"},{"id":"d","text":"Higher product quality"}]', 'Teams that neglect Sprint Retrospectives lose the opportunity to learn from their experience, leading to repeated mistakes and a lack of continuous improvement in both work processes and interpersonal relationships.'),

(6, 'Qual é uma disfunção comum quando há excesso de trabalho em progresso (WIP) em um Sprint?', 'fundamentals', '[{"id":"a","text":"Entrega mais rápida de cada item do Sprint Backlog"},{"id":"b","text":"Melhor organização do trabalho da equipe"},{"id":"c","text":"Mais itens finalizados ao final do Sprint"},{"id":"d","text":"Redução da qualidade e maior risco de não completar itens"}]', 'd', 'O excesso de WIP espalha a equipe por muitas tarefas ao mesmo tempo, reduzindo a qualidade e aumentando o risco de que itens não sejam completados, comprometendo a entrega de valor ao final do Sprint.', 'What is a common dysfunction when there is excessive work-in-progress (WIP) in a Sprint?', '[{"id":"a","text":"Faster delivery of every Sprint Backlog item"},{"id":"b","text":"Better organization of the team''s work"},{"id":"c","text":"More items finished at the end of the Sprint"},{"id":"d","text":"Reduced quality and higher risk of not completing items"}]', 'Excessive WIP spreads the team across too many tasks at once, reducing quality and increasing the risk that items are not completed, jeopardizing value delivery at the Sprint''s end.'),

(7, 'O que acontece se a equipe não conseguir completar todo o trabalho planejado para o Sprint?', 'fundamentals', '[{"id":"a","text":"O Sprint é estendido até que todo o trabalho seja finalizado"},{"id":"b","text":"O Scrum Master deve trabalhar horas extras para completar o trabalho"},{"id":"c","text":"O trabalho não finalizado retorna ao Product Backlog para repriorização"},{"id":"d","text":"A equipe é penalizada com um Sprint mais curto na próxima vez"}]', 'c', 'No Scrum, o timebox do Sprint é fixo e nunca é estendido. Se o trabalho planejado não for completado até o final do Sprint, o trabalho incompleto retorna ao Product Backlog e pode ser selecionado em um Sprint futuro, conforme a priorização do Product Owner.', 'What happens if the team cannot complete all the work planned for the Sprint?', '[{"id":"a","text":"The Sprint is extended until all work is completed"},{"id":"b","text":"The Scrum Master must work overtime to complete the work"},{"id":"c","text":"Incomplete work returns to the Product Backlog for reprioritization"},{"id":"d","text":"The team is penalized with a shorter Sprint next time"}]', 'In Scrum, the Sprint timebox is fixed and never extended. If planned work is not completed by the end of the Sprint, the incomplete work returns to the Product Backlog and can be selected in a future Sprint, according to the Product Owner''s prioritization.'),

(8, 'Quais são os três pilares do Scrum?', 'fundamentals', '[{"id":"a","text":"Visibilidade, inspeção e adaptação"},{"id":"b","text":"Transparência, inspeção e adaptação"},{"id":"c","text":"Comunicação, colaboração e entrega"},{"id":"d","text":"Planejamento, execução e revisão"}]', 'b', 'Os três pilares do Scrum são Transparência, Inspeção e Adaptação. Estes suportam a implementação do controle de processo empírico e a eficácia do framework Scrum.', 'What are the three pillars of Scrum?', '[{"id":"a","text":"Visibility, inspection and adaptation"},{"id":"b","text":"Transparency, inspection and adaptation"},{"id":"c","text":"Communication, collaboration and delivery"},{"id":"d","text":"Planning, execution and review"}]', 'The three pillars of Scrum are Transparency, Inspection, and Adaptation. These support the Scrum framework and the effectiveness of empirical process control.'),

(9, 'O que é um impedimento no contexto do Scrum?', 'fundamentals', '[{"id":"a","text":"Apenas problemas técnicos encontrados pelos Developers"},{"id":"b","text":"Um bug encontrado durante o Sprint"},{"id":"c","text":"Qualquer obstáculo que impeça a equipe de progredir"},{"id":"d","text":"Apenas problemas reportados pelo Product Owner"}]', 'c', 'Um impedimento no Scrum é qualquer coisa que impeça a equipe de avançar no Sprint. Pode ser interno (como um problema técnico) ou externo (como uma decisão de stakeholder). O Scrum Master ajuda a remover impedimentos.', 'What is an impediment in the Scrum context?', '[{"id":"a","text":"Any technical problem encountered by the Developers"},{"id":"b","text":"A bug found during the Sprint"},{"id":"c","text":"Any obstacle that blocks the team from progressing"},{"id":"d","text":"Only problems reported by the Product Owner"}]', 'An impediment in Scrum is anything that blocks the Developers from making progress. It can be technical, organizational, or external. The Scrum Master is responsible for helping remove impediments.'),

(10, 'O que é empirismo no Scrum?', 'fundamentals', '[{"id":"a","text":"Uma forma de rastrear velocidade"},{"id":"b","text":"Uma abordagem baseada em observação, inspeção e adaptação"},{"id":"c","text":"Um método para estimar story points"},{"id":"d","text":"Uma técnica para refinamento do Backlog"}]', 'b', 'O empirismo afirma que o conhecimento vem da experiência e da tomada de decisões baseadas no que é observado. O Scrum emprega uma abordagem iterativa e incremental para otimizar a previsibilidade e controlar o risco.', 'What is empiricism in Scrum?', '[{"id":"a","text":"A way to track velocity"},{"id":"b","text":"An approach based on observation, inspection and adaptation"},{"id":"c","text":"A method for estimating story points"},{"id":"d","text":"A technique for Backlog refinement"}]', 'Empiricism states that knowledge comes from experience and making decisions based on observation. Scrum uses an iterative and incremental approach to optimize predictability and control risk.'),

(11, 'Qual é o tamanho recomendado para um Scrum Team?', 'fundamentals', '[{"id":"a","text":"10 pessoas ou menos"},{"id":"b","text":"5-11 pessoas excluindo Scrum Master e Product Owner"},{"id":"c","text":"10-15 pessoas no total"},{"id":"d","text":"Não há tamanho fixo obrigatório"}]', 'a', 'Os Scrum Teams são tipicamente compostos por 10 ou menos pessoas. Em geral, equipes menores se comunicam melhor e são mais produtivas.', 'What is the recommended size for a Scrum Team?', '[{"id":"c","text":"10–15 people in total"},{"id":"d","text":"There is no fixed mandatory size"},{"id":"a","text":"10 people or fewer"},{"id":"b","text":"5–11 people excluding Scrum Master and Product Owner"}]', 'Scrum Teams are typically composed of 10 or fewer people. In general, smaller teams communicate better and are more productive.'),

(12, 'Qual afirmação sobre o Scrum está correta?', 'fundamentals', '[{"id":"a","text":"Scrum é um processo ou técnica para construir produtos"},{"id":"b","text":"Scrum é um framework abrangente com todas as ferramentas necessárias para gerenciamento de projetos"},{"id":"c","text":"Scrum é um framework dentro do qual você pode empregar vários processos e técnicas"},{"id":"d","text":"Scrum é uma metodologia que aumenta a produtividade da equipe"}]', 'c', 'Scrum é um framework leve que ajuda pessoas, equipes e organizações a gerar valor. Ele deixa espaço para as equipes escolherem as práticas que melhor se adequam ao seu contexto.', 'Which statement about Scrum is correct?', '[{"id":"a","text":"Scrum is a process or technique for building products"},{"id":"b","text":"Scrum is a comprehensive framework with all tools needed for project management"},{"id":"c","text":"Scrum is a framework within which you can employ various processes and techniques"},{"id":"d","text":"Scrum is a methodology that increases team productivity"}]', 'Scrum is a lightweight framework that helps people, teams, and organizations generate value. It leaves room for teams to choose the practices that best suit their context.'),

(13, 'Por que o Scrum é considerado "leve" (lightweight)?', 'fundamentals', '[{"id":"a","text":"Porque é fácil de aprender"},{"id":"b","text":"Porque tem poucas regras e papéis, sendo minimamente prescritivo"},{"id":"c","text":"Porque não requer documentação"},{"id":"d","text":"Porque é apenas para projetos pequenos"}]', 'b', 'O Scrum é deliberadamente leve. Ele define apenas o que é absolutamente necessário para cumprir seu propósito, deixando de fora todo o resto.', 'Why is Scrum considered ''lightweight''?', '[{"id":"a","text":"Because it is easy to learn"},{"id":"b","text":"Because it has few rules and roles, being minimally prescriptive"},{"id":"c","text":"Because it requires no documentation"},{"id":"d","text":"Because it is only for small projects"}]', 'Scrum is deliberately lightweight. It defines only what is absolutely necessary to fulfill its purpose, leaving out everything else.'),

(14, 'O que acontece quando um Sprint termina?', 'fundamentals', '[{"id":"a","text":"O Scrum Team recebe uma nova atribuição"},{"id":"b","text":"Um novo Sprint inicia imediatamente após"},{"id":"c","text":"O Scrum Team tem um período de descanso antes do próximo Sprint"},{"id":"d","text":"O Scrum Master avalia o desempenho da equipe"}]', 'b', 'Um novo Sprint inicia imediatamente após a conclusão do anterior, baseado no resultado da Sprint Review e no contexto atualizado.', 'What happens when a Sprint ends?', '[{"id":"a","text":"The Scrum Team is given a new assignment"},{"id":"b","text":"A new Sprint starts immediately afterward"},{"id":"c","text":"The Scrum Team has a rest period before the next Sprint"},{"id":"d","text":"The Scrum Master evaluates the team''s performance"}]', 'A new Sprint starts immediately after the conclusion of the previous one, based on the outcome of the Sprint Review and the updated context.'),

(15, 'Qual afirmação sobre transparência no Scrum é verdadeira?', 'fundamentals', '[{"id":"a","text":"Transparência é responsabilidade exclusiva do Scrum Master"},{"id":"b","text":"Transparência se aplica apenas ao progresso técnico do trabalho"},{"id":"c","text":"Transparência requer que o processo e o trabalho sejam visíveis para quem executa o trabalho e para quem recebe o trabalho"},{"id":"d","text":"Transparência significa que todas as informações estão disponíveis para qualquer pessoa na organização"}]', 'c', 'O processo e o trabalho emergente devem ser visíveis para aqueles que executam o trabalho e para aqueles que recebem o trabalho. A falta de transparência pode levar a decisões que reduzem o valor e aumentam o risco.', 'Which statement about transparency in Scrum is true?', '[{"id":"a","text":"Transparency is exclusively the Scrum Master''s responsibility"},{"id":"b","text":"Transparency only applies to the technical progress of the work"},{"id":"c","text":"Transparency requires the process and the work to be visible to those performing the work and those receiving the work"},{"id":"d","text":"Transparency means all information is available to anyone in the organization"}]', 'The process and the emerging work must be visible to those doing the work and those receiving the work. Lack of transparency may lead to decisions that reduce value and increase risk.'),

(16, 'Como o trabalho é dividido dentro de um Scrum Team?', 'fundamentals', '[{"id":"a","text":"Por especialidade técnica ou domínio"},{"id":"b","text":"Pelo Scrum Master em colaboração com gerentes funcionais"},{"id":"c","text":"Não há títulos para Developers independentemente do trabalho executado"},{"id":"d","text":"Pelo Product Owner baseado nas prioridades"}]', 'c', 'Dentro de um Scrum Team não há sub-equipes ou hierarquias; os Developers compartilham a responsabilidade e possuem todas as habilidades necessárias para criar valor a cada Sprint.', 'How is work divided within a Scrum Team?', '[{"id":"a","text":"By technical specialty or domain"},{"id":"b","text":"By the Scrum Master in collaboration with functional managers"},{"id":"c","text":"There are no titles for Developers regardless of the work performed"},{"id":"d","text":"By the Product Owner based on priorities"}]', 'Within a Scrum Team there are no sub‑teams or hierarchies; Developers share accountability and possess all the skills needed to create value each Sprint.'),

(17, 'O que significa auto-gestão (self-management) no Scrum?', 'fundamentals', '[{"id":"a","text":"Cada membro da equipe decide individualmente no que trabalhar"},{"id":"b","text":"A equipe decide internamente quem faz o quê, quando e como"},{"id":"c","text":"O Scrum Master gerencia as tarefas para a equipe"},{"id":"d","text":"Os Developers trabalham sem supervisão"}]', 'b', 'Os Scrum Teams são auto-gerenciados, escolhendo coletivamente quem faz o quê, quando e como, a fim de alcançar seus objetivos.', 'What does self‑management mean in Scrum?', '[{"id":"a","text":"Each team member individually decides what to work on"},{"id":"b","text":"The team internally decides who does what, when, and how"},{"id":"c","text":"The Scrum Master manages tasks for the team"},{"id":"d","text":"Developers work with no supervision"}]', 'Scrum Teams are self‑managing, collectively choosing who does what, when, and how in order to achieve their goals.'),

(18, 'Qual é uma das principais vantagens da estrutura com timebox do Scrum?', 'fundamentals', '[{"id":"a","text":"Permite adicionar mais trabalho quando a equipe termina cedo"},{"id":"b","text":"Reduz a complexidade ao limitar tempo e quantidade de trabalho"},{"id":"c","text":"Elimina a necessidade de planejamento detalhado"},{"id":"d","text":"Garante que todo o trabalho planejado será completado"}]', 'b', 'Os eventos com timebox do Scrum fornecem momentos regulares para inspeção e adaptação, reduzindo a complexidade do processo, minimizando desperdícios e focando no que é essencial.', 'What is one of the main advantages of Scrum''s time‑boxed structure?', '[{"id":"a","text":"It allows adding more work when the team finishes early"},{"id":"b","text":"It reduces complexity by limiting time and amount of work"},{"id":"c","text":"It eliminates the need for detailed planning"},{"id":"d","text":"It guarantees that all planned work will be completed"}]', 'Scrum''s time‑boxed events provide regular moments for inspection and adaptation, reducing process complexity, minimizing waste, and focusing on what is essential.'),

(19, 'O que significa dizer que o Scrum é "simples de entender, difícil de dominar"?', 'fundamentals', '[{"id":"a","text":"Seu framework é minimalista, mas a implementação eficaz requer prática"},{"id":"b","text":"É mais fácil de aprender do que outras metodologias ágeis"},{"id":"c","text":"É simples para iniciantes mas muito complexo para profissionais"},{"id":"d","text":"O Scrum Guide é curto mas a certificação é difícil"}]', 'a', 'O Scrum é simples de entender porque seu framework tem poucos elementos, mas dominá-lo é difícil porque exige compreensão profunda e aplicação disciplinada dos princípios empíricos.', 'What does it mean to say that Scrum is ''simple to understand, difficult to master''?', '[{"id":"d","text":"The Scrum Guide is short but the certification is hard"},{"id":"a","text":"Its framework is minimalist, but effective implementation requires practice"},{"id":"b","text":"It is easier to learn than other agile methodologies"},{"id":"c","text":"It is simple for beginners but very complex for professionals"}]', 'Scrum is simple to understand because its framework has few elements, but mastering it is hard because it demands deep understanding and disciplined application of empirical principles.');
