
-- Insert quiz questions 20-40 with both Portuguese and English translations
INSERT INTO quiz_questions (
    id, question, category_id, options, correct_answer, explanation,
    question_en, options_en, explanation_en
) VALUES
(20, 'Qual é o objetivo da Sprint Retrospective?', 'events', '[{"id":"a","text":"Criar um Release Plan"},{"id":"b","text":"Criar um plano de melhorias"},{"id":"c","text":"Entregar o Increment"},{"id":"d","text":"Calcular a Velocidade"}]', 'b', 'A Sprint Retrospective é uma oportunidade para o Scrum Team se inspecionar e criar um plano de melhorias a serem implementadas durante o próximo Sprint.', 'What is the goal of the Sprint Retrospective?', '[{"id":"a","text":"Create a Release Plan"},{"id":"b","text":"Create a plan for improvements"},{"id":"c","text":"Deliver the Increment"},{"id":"d","text":"Calculate Velocity"}]', 'The Sprint Retrospective is an opportunity for the Scrum Team to inspect itself and create a plan for improvements to be enacted during the next Sprint.'),

(21, 'Quem decide como o trabalho é dividido entre os Developers?', 'roles', '[{"id":"a","text":"Product Owner"},{"id":"b","text":"Scrum Master"},{"id":"c","text":"Os próprios Developers"},{"id":"d","text":"Gerente de Projeto"}]', 'c', 'Os Developers decidem internamente como realizar seu trabalho e dividi-lo entre si mesmos.', 'Who decides how work is divided among Developers?', '[{"id":"a","text":"Product Owner"},{"id":"b","text":"Scrum Master"},{"id":"c","text":"Developers themselves"},{"id":"d","text":"Project Manager"}]', 'The Developers decide internally how to accomplish their work and divide it amongst themselves.'),

(22, 'Quais são os valores do Scrum?', 'fundamentals', '[{"id":"a","text":"Transparência, Inspeção, Adaptação"},{"id":"b","text":"Compromisso, Foco, Abertura, Respeito e Coragem"},{"id":"c","text":"Comunicação, Colaboração, Visibilidade"},{"id":"d","text":"Agilidade, Eficiência, Qualidade, Inovação"}]', 'b', 'Os cinco valores do Scrum são: Compromisso, Foco, Abertura, Respeito e Coragem. Estes valores dão direção ao Scrum Team em relação ao seu trabalho, ações e comportamento.', 'What are the Scrum values?', '[{"id":"a","text":"Transparency, Inspection, Adaptation"},{"id":"b","text":"Commitment, Focus, Openness, Respect and Courage"},{"id":"c","text":"Communication, Collaboration, Visibility"},{"id":"d","text":"Agility, Efficiency, Quality, Innovation"}]', 'The five Scrum values are: Commitment, Focus, Openness, Respect and Courage. These values give direction to the Scrum Team with regard to their work, actions and behavior.'),

(23, 'Qual é o principal artefato que oferece transparência sobre o trabalho a ser feito?', 'artifacts', '[{"id":"a","text":"Release Burn Down"},{"id":"b","text":"Product Backlog"},{"id":"c","text":"Scrum Board"},{"id":"d","text":"Increment"}]', 'b', 'O Product Backlog é um artefato que oferece transparência sobre todo o trabalho necessário para o produto.', 'What is the main artifact that provides transparency about the work to be done?', '[{"id":"a","text":"Release Burn Down"},{"id":"b","text":"Product Backlog"},{"id":"c","text":"Scrum Board"},{"id":"d","text":"Increment"}]', 'The Product Backlog is an artifact that provides transparency about all the work needed for the product.'),

(24, 'Qual é o propósito do Product Backlog Refinement?', 'artifacts', '[{"id":"a","text":"Apenas repriorizar o Backlog"},{"id":"b","text":"Adicionar detalhes, estimativas e ordem aos itens do Backlog"},{"id":"c","text":"Escrever documentação"},{"id":"d","text":"Planejar Sprints"}]', 'b', 'Product Backlog Refinement é o ato de adicionar detalhes, estimativas e ordem aos itens do Product Backlog. É uma atividade contínua, não um evento.', 'What is the purpose of the Product Backlog Refinement?', '[{"id":"a","text":"To re-prioritize the Backlog only"},{"id":"b","text":"To add detail, estimates, and order to items in the Backlog"},{"id":"c","text":"To write documentation"},{"id":"d","text":"To plan Sprints"}]', 'Product Backlog Refinement is the act of adding detail, estimates, and order to items in the Product Backlog. It''s an ongoing activity, not an event.'),

(25, 'Quem é responsável por maximizar o valor do produto?', 'roles', '[{"id":"a","text":"Developers"},{"id":"b","text":"Scrum Master"},{"id":"c","text":"Product Owner"},{"id":"d","text":"Stakeholders"}]', 'c', 'O Product Owner é responsável por maximizar o valor do produto resultante do trabalho do Scrum Team.', 'Who is accountable for maximizing product value?', '[{"id":"a","text":"Developers"},{"id":"b","text":"Scrum Master"},{"id":"c","text":"Product Owner"},{"id":"d","text":"Stakeholders"}]', 'The Product Owner is accountable for maximizing the value of the product resulting from Scrum Team work.'),

(26, 'Qual afirmação sobre o Scrum está correta?', 'fundamentals', '[{"id":"a","text":"Scrum é um processo ou técnica para construir produtos"},{"id":"b","text":"Scrum é um framework abrangente com todas as ferramentas necessárias para gerenciamento de projetos"},{"id":"c","text":"Scrum é um framework dentro do qual você pode empregar vários processos e técnicas"},{"id":"d","text":"Scrum é uma metodologia que aumenta a produtividade da equipe"}]', 'c', 'Scrum é um framework leve que ajuda pessoas, equipes e organizações a gerar valor através de soluções adaptativas para problemas complexos. Ele não prescreve técnicas específicas, mas permite que as equipes escolham as práticas que melhor se adequam ao seu contexto.', 'Which statement about Scrum is correct?', '[{"id":"a","text":"Scrum is a process or technique for building products"},{"id":"b","text":"Scrum is a comprehensive framework with all tools needed for project management"},{"id":"c","text":"Scrum is a framework within which you can employ various processes and techniques"},{"id":"d","text":"Scrum is a methodology that increases team productivity"}]', 'Scrum is a lightweight framework that helps people, teams, and organizations generate value through adaptive solutions for complex problems. It does not prescribe specific techniques, but allows teams to choose practices that best suit their context.'),

(27, 'Qual é o foco de cada Sprint?', 'fundamentals', '[{"id":"a","text":"Entregar um produto completo"},{"id":"b","text":"Alcançar o Sprint Goal"},{"id":"c","text":"Aumentar a velocidade"},{"id":"d","text":"Finalizar todos os itens do Backlog"}]', 'b', 'Cada Sprint tem um Sprint Goal que oferece um objetivo único e abrangente para a equipe. O objetivo dá foco e flexibilidade à equipe em relação ao trabalho realizado dentro do Sprint.', 'What is the focus of each Sprint?', '[{"id":"a","text":"Deliver a complete product"},{"id":"b","text":"Achieve the Sprint Goal"},{"id":"c","text":"Increase velocity"},{"id":"d","text":"Finish all Backlog items"}]', 'Each Sprint has a Sprint Goal that provides a single, overarching objective for the team. The goal gives the team focus and flexibility regarding the work undertaken within the Sprint.'),

(28, 'Com que frequência o Product Backlog deve ser refinado?', 'artifacts', '[{"id":"a","text":"Uma vez por Sprint"},{"id":"b","text":"Diariamente"},{"id":"c","text":"Continuamente durante cada Sprint"},{"id":"d","text":"Apenas antes do Sprint Planning"}]', 'c', 'Product Backlog Refinement é um processo contínuo durante cada Sprint, conforme necessário. Não é um evento ou cerimônia.', 'How often should the Product Backlog be refined?', '[{"id":"a","text":"Once per Sprint"},{"id":"b","text":"Daily"},{"id":"c","text":"Ongoing through each Sprint"},{"id":"d","text":"Only before Sprint Planning"}]', 'Product Backlog Refinement is an ongoing process throughout each Sprint as needed. It is not an event or ceremony.'),

(29, 'Por que o Scrum é considerado "leve" (lightweight)?', 'fundamentals', '[{"id":"a","text":"Porque é fácil de aprender"},{"id":"b","text":"Porque tem poucas regras e papéis"},{"id":"c","text":"Porque não requer documentação"},{"id":"d","text":"Porque é apenas para projetos pequenos"}]', 'b', 'O Scrum é intencionalmente leve. Ele define apenas as partes necessárias para implementar a teoria do Scrum. O framework do Scrum é minimalista, não contendo nada que não seja absolutamente necessário para cumprir seu propósito.', 'Why is Scrum considered ''lightweight''?', '[{"id":"a","text":"Because it is easy to learn"},{"id":"b","text":"Because it has few rules and roles"},{"id":"c","text":"Because it does not require documentation"},{"id":"d","text":"Because it is only for small projects"}]', 'Scrum is intentionally lightweight. It defines only the parts necessary to implement Scrum theory. The Scrum framework is minimalist, containing nothing that is not absolutely necessary to accomplish its purpose.'),

(30, 'Quem é dono do Product Backlog?', 'roles', '[{"id":"a","text":"Scrum Master"},{"id":"b","text":"Developers"},{"id":"c","text":"Product Owner"},{"id":"d","text":"Stakeholders"}]', 'c', 'O Product Owner é responsável pelo Product Backlog, incluindo seu conteúdo, disponibilidade e ordenação.', 'Who owns the Product Backlog?', '[{"id":"a","text":"Scrum Master"},{"id":"b","text":"Developers"},{"id":"c","text":"Product Owner"},{"id":"d","text":"Stakeholders"}]', 'The Product Owner is responsible for the Product Backlog, including its content, availability, and ordering.'),

(31, 'O que deve acontecer se um membro da equipe ficar doente durante o Sprint?', 'fundamentals', '[{"id":"a","text":"O Scrum Master substitui o membro da equipe"},{"id":"b","text":"O Sprint é pausado"},{"id":"c","text":"Outros Developers cobrem pelo membro da equipe para ajudar a alcançar o Sprint Goal"},{"id":"d","text":"O Sprint é cancelado"}]', 'c', 'O Scrum Team como um todo é responsável pelo Sprint Goal. Se alguém estiver ausente, os membros restantes da equipe fazem o seu melhor para cumprir o Sprint Goal.', 'What should happen if a team member is sick during the Sprint?', '[{"id":"a","text":"The Scrum Master replaces the team member"},{"id":"b","text":"The Sprint is paused"},{"id":"c","text":"Other Developers cover for the team member to help reach the Sprint Goal"},{"id":"d","text":"The Sprint is canceled"}]', 'The Scrum Team as a whole is responsible for the Sprint Goal. If someone is absent, the remaining team members do their best to meet the Sprint Goal.'),

(32, 'Qual é o melhor momento para fazer mudanças no Sprint Backlog?', 'artifacts', '[{"id":"a","text":"A qualquer momento"},{"id":"b","text":"Apenas durante o Sprint Planning"},{"id":"c","text":"Durante o Sprint, conforme necessário, pelos Developers"},{"id":"d","text":"Após o Sprint terminar"}]', 'c', 'Os Developers podem atualizar o Sprint Backlog conforme mais se aprende sobre o trabalho necessário para alcançar o Sprint Goal, mas apenas durante o Sprint atual.', 'What is the best time to make changes to the Sprint Backlog?', '[{"id":"a","text":"Any time"},{"id":"b","text":"Only during Sprint Planning"},{"id":"c","text":"During the Sprint, as needed, by the Developers"},{"id":"d","text":"After the Sprint ends"}]', 'The Developers can update the Sprint Backlog as more is learned about the work needed to achieve the Sprint Goal, but only during the current Sprint.'),

(33, 'O que acontece quando um Sprint termina?', 'fundamentals', '[{"id":"a","text":"O Scrum Team recebe uma nova atribuição"},{"id":"b","text":"Um novo Sprint inicia imediatamente após"},{"id":"c","text":"O Scrum Team tem um período de descanso antes do próximo Sprint"},{"id":"d","text":"O Scrum Master avalia o desempenho da equipe"}]', 'b', 'Um novo Sprint inicia imediatamente após a conclusão do anterior. Os Sprints são contínuos; apenas o conteúdo e foco podem mudar de um Sprint para outro baseado no resultado da Sprint Review e contexto atualizado do trabalho.', 'What happens when a Sprint ends?', '[{"id":"a","text":"The Scrum Team receives a new work assignment"},{"id":"b","text":"A new Sprint starts immediately after"},{"id":"c","text":"The Scrum Team has a rest period before the next Sprint"},{"id":"d","text":"The Scrum Master evaluates the team''s performance"}]', 'A new Sprint starts immediately after the conclusion of the previous Sprint. Sprints are continuous; only the content and focus may change from one Sprint to another based on the Sprint Review outcome and updated work context.'),

(34, 'Quem pode cancelar um Sprint?', 'fundamentals', '[{"id":"a","text":"Scrum Master"},{"id":"b","text":"Product Owner"},{"id":"c","text":"Developers"},{"id":"d","text":"Stakeholders"}]', 'b', 'Apenas o Product Owner tem autoridade para cancelar o Sprint. Um Sprint seria cancelado se o Sprint Goal se tornasse obsoleto.', 'Who can cancel a Sprint?', '[{"id":"a","text":"Scrum Master"},{"id":"b","text":"Product Owner"},{"id":"c","text":"Developers"},{"id":"d","text":"Stakeholders"}]', 'Only the Product Owner has the authority to cancel the Sprint. A Sprint would be canceled if the Sprint Goal becomes obsolete.'),

(35, 'O que é entregue como parte de um Increment do Scrum?', 'artifacts', '[{"id":"a","text":"Todos os itens do Product Backlog completados"},{"id":"b","text":"Uma funcionalidade solicitada pelos stakeholders"},{"id":"c","text":"Um pacote de release"},{"id":"d","text":"Sprint Burndown Chart"}]', 'a', 'O Increment é a soma de todos os itens do Product Backlog completados durante um Sprint e o valor dos incrementos de todos os Sprints anteriores. Ao final de um Sprint, o novo Increment deve estar "Done" e em condição utilizável.', 'What is delivered as part of a Scrum Increment?', '[{"id":"a","text":"All completed Product Backlog items"},{"id":"b","text":"A feature requested by stakeholders"},{"id":"c","text":"A release package"},{"id":"d","text":"Sprint Burndown Chart"}]', 'The Increment is the sum of all the Product Backlog items completed during a Sprint and the value of the increments of all previous Sprints. At the end of a Sprint, the new Increment must be ''Done'' and in usable condition.'),

(36, 'Qual evento do Scrum é tipicamente limitado a 15 minutos?', 'events', '[{"id":"a","text":"Sprint Planning"},{"id":"b","text":"Sprint Review"},{"id":"c","text":"Daily Scrum"},{"id":"d","text":"Sprint Retrospective"}]', 'c', 'A Daily Scrum é limitada a 15 minutos.', 'Which Scrum event is typically timeboxed to 15 minutes?', '[{"id":"a","text":"Sprint Planning"},{"id":"b","text":"Sprint Review"},{"id":"c","text":"Daily Scrum"},{"id":"d","text":"Sprint Retrospective"}]', 'The Daily Scrum is timeboxed to 15 minutes.'),

(37, 'Qual afirmação sobre transparência no Scrum é verdadeira?', 'fundamentals', '[{"id":"a","text":"Transparência é responsabilidade exclusiva do Scrum Master"},{"id":"b","text":"Transparência se aplica apenas ao progresso técnico do trabalho"},{"id":"c","text":"Transparência requer que o processo e o trabalho sejam visíveis para quem executa e quem recebe o trabalho"},{"id":"d","text":"Transparência significa que todas as informações estão disponíveis para qualquer pessoa na organização"}]', 'c', 'O processo emergente e o trabalho devem ser visíveis para aqueles que executam o trabalho bem como para aqueles que recebem o trabalho. No Scrum, decisões importantes são baseadas no estado percebido de seus três artefatos formais. Artefatos que têm baixa transparência podem levar a decisões que diminuem o valor e aumentam o risco.', 'Which statement about transparency in Scrum is true?', '[{"id":"a","text":"Transparency is the exclusive responsibility of the Scrum Master"},{"id":"b","text":"Transparency only applies to technical work progress"},{"id":"c","text":"Transparency requires the process and work to be visible to those who perform and receive the work"},{"id":"d","text":"Transparency means all information is available to anyone in the organization"}]', 'The emergent process and work must be visible to those performing the work as well as those receiving the work. In Scrum, important decisions are based on the perceived state of its three formal artifacts. Artifacts that have low transparency can lead to decisions that diminish value and increase risk.'),

(38, 'Com que frequência a Definition of Done deve ser atendida?', 'artifacts', '[{"id":"a","text":"Apenas para o primeiro Sprint"},{"id":"b","text":"Apenas para funcionalidades críticas"},{"id":"c","text":"Todo Increment"},{"id":"d","text":"Sempre que os Developers tiverem tempo"}]', 'c', 'Todo Increment deve atender à Definition of Done. Trabalho que não atende à Definition of Done não é considerado parte do Increment.', 'How often should the Definition of Done be met?', '[{"id":"a","text":"Only for the first Sprint"},{"id":"b","text":"Only for critical features"},{"id":"c","text":"Every Increment"},{"id":"d","text":"Whenever Developers have time"}]', 'Every Increment must meet the Definition of Done. Work not meeting the Definition of Done is not considered part of the Increment.'),

(39, 'Qual é o papel do Product Owner durante o Sprint Planning?', 'roles', '[{"id":"a","text":"Atribuir tarefas aos Developers"},{"id":"b","text":"Esclarecer itens do Product Backlog e Product Goal"},{"id":"c","text":"Facilitar o evento como moderador principal"},{"id":"d","text":"Revisar análises do Sprint anterior"}]', 'b', 'Durante o Sprint Planning, o Product Owner garante que os participantes estejam preparados para discutir os itens mais importantes do Product Backlog e como eles se relacionam com o Product Goal.', 'What is the role of the Product Owner during Sprint Planning?', '[{"id":"a","text":"To assign tasks to Developers"},{"id":"b","text":"To clarify Product Backlog items and Product Goal"},{"id":"c","text":"To facilitate the event as the main moderator"},{"id":"d","text":"To review previous Sprint analytics"}]', 'During Sprint Planning, the Product Owner ensures that attendees are prepared to discuss the most important Product Backlog items and how they map to the Product Goal.'),

(40, 'O que significa dizer que o Product Owner é "uma pessoa, não um comitê"?', 'roles', '[{"id":"a","text":"O Product Owner nunca deve consultar ninguém"},{"id":"b","text":"Uma única pessoa deve ter autoridade final sobre o Product Backlog"},{"id":"c","text":"O Product Owner não deve fazer parte de um comitê de produto"},{"id":"d","text":"O Product Owner não pode representar desejos dos stakeholders"}]', 'b', 'Significa que uma única pessoa deve ter autoridade final e responsabilidade pelas decisões do Product Backlog. Embora o Product Owner possa representar os interesses de muitos stakeholders e possa coletar inputs, no final apenas uma pessoa possui as decisões do Product Backlog.', 'What does it mean to say the Product Owner is ''one person, not a committee''?', '[{"id":"a","text":"The Product Owner never consults others"},{"id":"b","text":"A single person must have final authority over the Product Backlog"},{"id":"c","text":"The Product Owner should not be part of a product committee"},{"id":"d","text":"The Product Owner cannot represent stakeholder wishes"}]', 'It means that a single person must have the final authority and accountability for Product Backlog decisions. While the Product Owner may represent the interests of many stakeholders and can gather input, ultimately only one person owns the Product Backlog decisions.');
