// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdzcdqdeyrcmpnnputvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kemNkcWRleXJjbXBubnB1dHZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDE1MTksImV4cCI6MjA2MzY3NzUxOX0.U30JzYsI8RUmDVAZ08ezYCYHYXgi0mhmivTn1Qn99bc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);