// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdlctymidbhruswvxozy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkbGN0eW1pZGJocnVzd3Z4b3p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NzEyNTksImV4cCI6MjA1OTA0NzI1OX0.t8yOIvJ8b-3rnaC5QmqqXXBDtn4cjUAJyF-ww3t2mns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);